# Generated by Django 4.2.16 on 2025-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
