# Generated by Django 4.2.16 on 2025-03-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_customer_username_alter_worker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='workers.customer', unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='workers.worker', unique=True),
        ),
    ]
