# Generated by Django 4.2.16 on 2025-03-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_customer_address_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
