# Generated by Django 4.2.16 on 2025-03-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_customer_password_remove_worker_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
