# Generated by Django 4.2.16 on 2025-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_customer_user_alter_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
