# Generated by Django 4.2.16 on 2025-03-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_alter_customer_user_alter_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='booked_by',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
