# Generated by Django 4.2.16 on 2025-03-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_remove_customer_booking_remove_worker_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
